name: Front-End CI Actions
on: [push]
jobs:
  lint:
    runs-on: macos-latest
steps:
  - uses: actions/checkout@v2
  - name: Package Install
    run: npm install
  - name: TypeScript Compile
    run: npm run lint:ts 
  - name: Run eslint-and-prettier
    run: npm run lint