name: Front-End CI Actions
on: [push]
jobs:
  eslint-and-prettier:
    runs-on: macos-latest
  steps:
    - name: Package Install
      run: npm install
    - name: TypeScript Compile
      run: npm run lint:ts 
    - name: Run eslint-and-prettier
      run: npm run lint