name: Front-End CI Actions
on: [push]
jobs:
  eslint-and-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Package Install
        run: npm install
      - name: Run eslint-and-prettier
        run: npm run lint
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Apply Prettier Change