name: Front-End CI Actions
on: [push]
jobs:
  eslint-and-prettier:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package Install
        run: npm install
      - name: Run eslint-and-prettier
        run: eslint --fix ./ --ext ts,tsx